blossom/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.storage import staticfiles_storage
from django.views.generic.base import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path(
        "favicon.ico",
        RedirectView.as_view(url=staticfiles_storage.url("favicon.ico")),
    ),
    path('', include('ccf.urls')),
    path('', include('users.urls')),
]

ccf/urls.py
from django.urls import path
from . import views
import ccf.symbols


# register our namespace
app_name = 'ccf'

urlpatterns_notes = [
    # page to create a note for a client
    path(
        'client/<int:client_id>/note/new/',
        views.NoteCreateView.as_view(
            extra_context={
                'title': 'New Note',
                'model': 'Note',
                'action': 'Add',
                'cancel_url': 'ccf:client-detail',
                'client_tab': ccf.symbols.CLIENT_TAB_NOTES,
            },
        ),
        name='note-create',
    ),
    # page to update a note for a client
    path(
        'client/<int:client_id>/note/<int:pk>/update/',
        views.NoteUpdateView.as_view(
            extra_context={
                'title': 'Update Note',
                'model': 'Note',
                'action': 'Update',
                'cancel_url': 'ccf:client-detail',
                'client_tab': ccf.symbols.CLIENT_TAB_NOTES,
            },
        ),
        name='note-update',
    ),
    # page to view a note for a client
    path(
        'client/<int:client_id>/note/<int:pk>/detail/',
        views.NoteDetailView.as_view(
            extra_context={
                'title': 'Note Detail',
                'model': 'Note',
                'cancel_url': 'ccf:client-detail',
                'update_url': 'ccf:note-update',
                'delete_url': 'ccf:note-delete',
                'client_tab': ccf.symbols.CLIENT_TAB_NOTES,
            },
        ),
        name='note-detail',
    ),
    # page to delete a note
    path(
        'client/<int:client_id>/note/<int:pk>/delete/',
        views.NoteDeleteView.as_view(
            extra_context={
                'title': 'Delete Note',
                'model': 'Note',
                'name': 'title',
            },
        ),
        name='note-delete',
    ),
]

urlpatterns_treatments = [
    # page to create a treatment for a client
    path(
        'client/<int:client_id>/treatment/new/',
        views.TreatmentCreateView.as_view(
            extra_context={
                'title': 'New Treatment',
                'model': 'Treatment',
                'action': 'Add',
                'cancel_url': 'ccf:client-detail',
                'client_tab': ccf.symbols.CLIENT_TAB_TREATMENTS,
            },
        ),
        name='treatment-create',
    ),
    # page to update a treatment for a client
    path(
        'client/<int:client_id>/treatment/<int:pk>/update/',
        views.TreatmentUpdateView.as_view(
            extra_context={
                'title': 'Update Treatment',
                'model': 'Treatment',
                'action': 'Update',
                'cancel_url': 'ccf:client-detail',
                'client_tab': ccf.symbols.CLIENT_TAB_TREATMENTS,
            },
        ),
        name='treatment-update',
    ),
    # page to view a treatment for a client
    path(
        'client/<int:client_id>/treatment/<int:pk>/detail/',
        views.TreatmentDetailView.as_view(
            extra_context={
                'title': 'Treatment Detail',
                'model': 'Treatment',
                'cancel_url': 'ccf:client-detail',
                'update_url': 'ccf:treatment-update',
                'delete_url': 'ccf:treatment-delete',
                'client_tab': ccf.symbols.CLIENT_TAB_TREATMENTS,
            },
        ),
        name='treatment-detail',
    ),
    # page to delete a treatment
    path(
        'client/<int:client_id>/treatment/<int:pk>/delete/',
        views.TreatmentDeleteView.as_view(
            extra_context={
                'title': 'Delete Treatment',
                'model': 'Treatment',
                'name': 'title',
            },
        ),
        name='treatment-delete',
    ),
]

urlpatterns = [
    # home page; lists all clients
    path(
        '',
        views.ClientListView.as_view(
            extra_context={'title': 'Home'},
        ),
        name='home',
    ),
    # user page; lists all clients of a user
    path(
        'user/<str:username>/',
        views.UserClientListView.as_view(
            extra_context={
                'title': 'Clients'
            },
        ),
        name='user-clients',
    ),
    # page to view single client; this is a tabbed view
    # <int:tab> selects the tab to show
    path(
        'client/<int:client_id>/detail/<int:tab>/',
        views.ClientDetailView.as_view(
            extra_context={
                'title': 'Client Detail'
            },
        ),
        name='client-detail',
    ),
    # page to create a client
    path(
        'client/new/',
        views.ClientCreateView.as_view(
            extra_context={
                'title': 'New Client',
                'model': 'User',
                'action': 'Add',
                'cancel_url': 'ccf:user-clients',
            },
        ),
        name='client-create',
    ),
    # page to update a client
    path(
        'client/<int:client_id>/update/',
        views.ClientUpdateView.as_view(
            extra_context={
                'title': 'Update Client',
                'model': 'Client',
                'action': 'Update',
                'cancel_url': 'ccf:client-detail',
                'client_tab': ccf.symbols.CLIENT_TAB_DETAILS,
            },
        ),
        name='client-update',
    ),
    # page to delete a client
    path(
        'client/<int:client_id>/delete/',
        views.ClientDeleteView.as_view(
            extra_context={
                'title': 'Delete Client',
                'model': 'Client',
                'name': 'display_name',
            },
        ),
        name='client-delete',
    ),
    # page to update medical details of a client
    path(
        'client/<int:client_id>/medical/update/',
        views.MedicalUpdateView.as_view(
            extra_context={
                'title': 'Update Medical',
                'model': 'Medical',
                'action': 'Update',
                'cancel_url': 'ccf:client-detail',
                'client_tab': ccf.symbols.CLIENT_TAB_MEDICAL,
            },
        ),
        name='medical-update',
    ),
    # page to update consultation details of a client
    path(
        'client/<int:client_id>/consultation/update/',
        views.ConsultationUpdateView.as_view(
            extra_context={
                'title': 'Update Consultation',
                'model': 'Consultation',
                'action': 'Update',
                'cancel_url': 'ccf:client-detail',
                'client_tab': ccf.symbols.CLIENT_TAB_CONSULTATION,
            },
        ),
        name='consultation-update',
    ),
    # about page
    path(
        'about/',
        views.about,
        name='about',
    ),
]

urlpatterns.extend(urlpatterns_notes)
urlpatterns.extend(urlpatterns_treatments)

users/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
from . import views


# register our namespace
app_name = 'users'

urlpatterns = [
    path(
        'register/',
        views.register,
        name='register',
    ),
    path(
        'profile/',
        views.profile,
        name='profile',
    ),
    path(
        'login/',
        views.MyLoginView.as_view(
            template_name='users/login.html',
            extra_context={'title': 'Login'},
        ),
        name='login',
    ),
    path(
        'logout/',
        auth_views.LogoutView.as_view(
            template_name='users/logout.html',
            extra_context={'title': 'Logged Out'},
        ),
        name='logout',
    ),
]

# get correct location for media files in DEBUG mode
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ccf/models.py
from django.db import models
from django.utils.text import capfirst
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
from django.shortcuts import (
    get_object_or_404,
)
import datetime
import ccf.symbols


def get_default_date():
    return datetime.date(1970, 1, 1)


# each class in the model corresponds to a database table
class Client(models.Model):
    # each attribute corresponds to a field in the table
    #
    # CharField: single-line text
    display_name = models.CharField(max_length=24)
    # timezone.now: time when client is added
    date_added = models.DateTimeField(default=timezone.now)
    # CASCADE: if user is deleted, then all clients will be deleted as well
    therapist = models.ForeignKey(User, on_delete=models.CASCADE)
    full_name = models.CharField(max_length=50, default='')
    address = models.CharField(max_length=50, default='')
    phone = models.CharField(max_length=18, default='')
    mobile = models.CharField(max_length=18, default='')
    email = models.EmailField(max_length=50, default='')
    profession = models.CharField(max_length=50, default='')
    dob = models.DateField(default=get_default_date)

    def __str__(self):
        return self.display_name

    def get_detail_fields(self):
        return [
            (capfirst(field.verbose_name), field.value_from_object(self))
            for field in self._meta.fields
            if field.name not in (
                'id', 'display_name', 'therapist', 'date_added'
            )
        ]

    # return the canonical URL for an object
    def get_absolute_url(self):
        return reverse(
            'ccf:client-detail',
            kwargs={
                'client_id': self.pk,
                'tab': ccf.symbols.CLIENT_TAB_DETAILS
            },
        )


class Medical(models.Model):
    # connect our user model to django's user model
    # on delete, delete everything i.e. cascade
    client = models.OneToOneField(Client, on_delete=models.CASCADE)
    # TextField: multi-line text, use kwarg 'verbose_name' to set name
    # displayed in forms (done here as an example)
    allergies = models.TextField(
        verbose_name='Allergies',
        default='',
    )
    chronic_skin_conditions = models.TextField(default='')
    illnesses_and_disorders = models.TextField(default='')
    cosmetic_procedures = models.TextField(default='')
    medications = models.TextField(default='')
    pregnancy = models.TextField(default='')
    # this will be updated when the note is edited
    date_updated = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return f'{self.client.display_name} Medical'

    def get_detail_fields(self):
        return [
            (capfirst(field.verbose_name), field.value_from_object(self))
            for field in self._meta.fields
            if field.name not in (
                'id', 'client', 'date_updated'
            )
        ]

    def get_absolute_url(self):
        # page to redirect to after creating new object
        return reverse(
            'ccf:client-detail',
            kwargs={
                'client_id': self.pk,
                'tab': ccf.symbols.CLIENT_TAB_MEDICAL
            },
        )


class Consultation(models.Model):
    # connect our user model to django's user model
    # on delete, delete everything i.e. cascade
    client = models.OneToOneField(Client, on_delete=models.CASCADE)
    # TextField: multi-line text
    skin_type = models.TextField(default='')
    skin_conditions = models.TextField(default='')
    concerns = models.TextField(default='')
    lash_colour = models.TextField(default='')
    eyebrow_colour = models.TextField(default='')
    # this will be updated when the note is edited
    date_updated = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return f'{self.client.display_name} Consultation'

    def get_detail_fields(self):
        data = [
            (capfirst(field.verbose_name), field.value_from_object(self))
            for field in self._meta.fields
            if field.name not in (
                'id', 'client', 'date_updated'
            )
        ]
        return data

    def get_absolute_url(self):
        # page to redirect to after creating new object
        return reverse(
            'ccf:client-detail',
            kwargs={
                'client_id': self.pk,
                'tab': ccf.symbols.CLIENT_TAB_CONSULTATION
            },
        )


class Note(models.Model):
    # CharField: single-line text
    title = models.CharField(max_length=100)
    # TextField: multi-line text
    content = models.TextField()
    # this will be updated when the note is edited
    date_updated = models.DateTimeField(default=timezone.now)
    # CASCADE: if client is deleted, then all notes will be deleted as well
    client = models.ForeignKey(Client, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

    # our generic templates use 'generic_object.display_name'
    # to refer to the instance name
    @property
    def display_name(self):
        return self.title

    def get_absolute_url(self):
        # page to redirect to after creating new object
        return reverse(
            'ccf:note-detail',
            kwargs={
                'client_id': self.client_id,
                'pk': self.pk,
            }
        )


class Treatment(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
    # this will not be updated when the treatment is edited
    date_treated = models.DateTimeField(default=timezone.now)
    # CASCADE: if client is deleted, then all treatments will be deleted as well
    client = models.ForeignKey(Client, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

    # our generic templates use 'generic_object.display_name'
    # to refer to the instance name
    @property
    def display_name(self):
        return self.title

    def get_absolute_url(self):
        # page to redirect to after creating new object
        return reverse(
            'ccf:treatment-detail',
            kwargs={
                'client_id': self.client_id,
                'pk': self.pk,
            }
        )

ccf/templates/ccf/about.html
{% extends "ccf/base.html" %}
{% block content %}
    <h1>About Page</h1>
    <div>App version is {{ CCF_APP_VERSION }}</div>
    <div>Current git hash is <code>{{ git_hash }}</code></div>
{% endblock content %}

ccf/templates/ccf/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'ccf/css/bootstrap.min.css' %}">
    <!-- Our CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'ccf/css/ccf.main.css' %}">
    <!-- Our title -->
    {% if title %}
        <title>CCF - {{ title }}</title>
    {% else %}
        <title>CCF - No Title</title>
    {% endif %}
  </head>
  <body>
     <header class="site-header">
       <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
        <div class="container-fluid">
          <a class="navbar-brand" href="{% url 'ccf:user-clients' request.user %}">CCF</a>
          {% if request.user.is_authenticated %}
          <a class="navbar-brand" href="{% url 'ccf:client-create' %}">New Client</a>
          {% endif %}
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarToggle">
            <ul class="navbar-nav me-auto mb-2 mb-md-0">
              <a class="nav-item nav-link" href="{% url 'ccf:about' %}">About</a>
              {% if request.user.is_authenticated %}
                <li class="nav-item">
                  <a class="nav-link" href="#"
                    onClick="document.getElementById('logoutform').submit()">
                    Logout
                  </a>
                </li>
                <form id="logoutform" method="POST" action="{% url 'users:logout' %}">
                  {% csrf_token %}
                  <input type="hidden">
                </form>
              {% else %}
                <a class="nav-item nav-link" href="{% url 'users:login' %}">Login</a>
                <a class="nav-item nav-link" href="{% url 'users:register' %}">Register</a>
              {% endif %}
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <main role="main" class="container">
      <div class="row">
        <div class="col-md-8">
          {% if messages %}
            {% for message in messages %}
              <div class="alert alert-{{ message.tags }}">
                {{ message }}
              </div>
            {% endfor %}
          {% endif %}
          {% block content %}{% endblock %}
        </div>
      </div>
    </main>
   <!-- Optional JavaScript -->
    <script src="{% static 'ccf/js/bootstrap.bundle.min.js' %}"></script>
  </body>
</html>

ccf/templates/ccf/client_confirm_delete.html
{% extends "ccf/base.html" %}
{% block content %}
  <div class="content-section">
    <form method="POST">
      {% csrf_token %}
      <fieldset class="form-group">
        <legend class="border-bottom mb-4">Delete Client</legend>
        <h2>Are you sure you want to delete client "{{ object.friendly_name }}"</h2>
      </fieldset>
      <div class="form-group">
        <button class="btn btn-outline-danger" type="submit">Yes, Delete</button>
        <a class="btn btn-outline-secondary" href="{% url 'ccf:client-detail' pk=object.id tab=0 %}">Cancel</a>
      </div>
    </form>
  </div>
{% endblock content %}

ccf/templates/ccf/client_detail.html
{% extends "ccf/base.html" %}
{% block content %}
{% load custom_filters %}
  <article class="media content-section">
    <div class="media-body">
      <div class="article-metadata">
        <small class="text-muted">Client of</small>
        <a class="mr-2" href="{% url 'ccf:user-clients' object.therapist.username %}">{{ client.therapist }}</a>
        <!-- we use a filter on date_added to get desired formatting -->
        <small class="text-muted">since {{ object.date_added|date:"d F, Y" }}</small>
        <!-- the 'div' moves the button to the next line -->
        <div>
          <h2 style="display:inline" class="article-title">{{ object.display_name }}</h2>
          {% if object.therapist == user %}
            <a class="btn btn-danger btn-sm mt-0 mb-1" href="{% url 'ccf:client-delete' object.id %}">Delete Client</a>
          {% endif %}
        </div>
      </div>
      <p class="article-content">{{ object.content }}</p>
      <ul class="nav nav-tabs px-1 mb-1" role="tablist">
        <li class="nav-item" role="presentation">
          <a class="nav-link px-1 {{ tab_to_open|active_tab:'0' }}" id="simple-tab-0" data-bs-toggle="tab" href="#simple-tabpanel-0" role="tab">details</a>
        </li>
        <li class="nav-item" role="presentation">
          <a class="nav-link px-1 {{ tab_to_open|active_tab:'1' }}" id="simple-tab-1" data-bs-toggle="tab" href="#simple-tabpanel-1" role="tab">notes</a>
        </li>
        <li class="nav-item" role="presentation">
          <a class="nav-link px-1 {{ tab_to_open|active_tab:'2' }}" id="simple-tab-2" data-bs-toggle="tab" href="#simple-tabpanel-2" role="tab">treatments</a>
        </li>
        <li class="nav-item" role="presentation">
          <a class="nav-link px-1 {{ tab_to_open|active_tab:'3' }}" id="simple-tab-3" data-bs-toggle="tab" href="#simple-tabpanel-3" role="tab">medical</a>
        </li>
        <li class="nav-item" role="presentation">
          <a class="nav-link px-1 {{ tab_to_open|active_tab:'4' }}" id="simple-tab-4" data-bs-toggle="tab" href="#simple-tabpanel-4" role="tab">consultation</a>
        </li>
      </ul>
      <div class="tab-content pt-2" id="tab-content">
        <div class="tab-pane {{ tab_to_open|active_tab:CLIENT_TAB_DETAILS }}" id="simple-tabpanel-0" role="tabpanel">
          <table class="table table-sm table-hover table-bordered" style="width:auto">
          {% for label, value in object.get_detail_fields %}
            <tr>
              <td>{{ label }}</td>
              <td>{{ value }}</td>
            </tr>
          {% endfor %}
          </table>
        {% if object.therapist == user %}
          <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{% url 'ccf:client-update' object.id %}">Update</a>
        {% endif %}
        </div>
        <div class="tab-pane {{ tab_to_open|active_tab:CLIENT_TAB_NOTES }}" id="simple-tabpanel-1" role="tabpanel">
          <table class="table table-sm table-hover table-bordered" style="width:auto">
          {% for note in notes %}
          <tr>
            <td><a href="{% url 'ccf:note-detail' client_id=object.id pk=note.id %}">{{ note.title }}</a></td>
            <td>{{ note.content|truncate_field:'40' }}</td>
          </tr>
          {% empty %}
          Client has no notes
          {% endfor %}
          </table>
          {% if notes.is_paginated %}
          <div>
            {% if notes.has_previous %}
              <a class="btn btn-outline-info mx-2 my-2 px-2 py-2" href="../{{ CLIENT_TAB_NOTES }}/?page1=1">&#x27EA</a> {# first #}
              <a class="btn btn-outline-info mx-2 my-2 px-2 py-2" href="../{{ CLIENT_TAB_NOTES }}/?page1={{ notes.previous_page_number }}">&#x27E8</a> {# previous #}
            {% endif %}
            {% for num in notes.paginator.page_range %}
              {% if notes.number == num %}
                <a class="btn btn-info mx-2 my-2 px-2 py-2" href="../{{ CLIENT_TAB_NOTES }}/?page1={{ num }}">{{ num }}</a>
              {% elif num > notes.number|add:'-3' and num < notes.number|add:'3' %}
                <a class="btn btn-outline-info mx-2 my-2 px-2 py-2" href="../{{ CLIENT_TAB_NOTES }}/?page1={{ num }}">{{ num }}</a>
              {% endif %}
            {% endfor %}
            {% if notes.has_next %}
              <a class="btn btn-outline-info mx-2 my-2 px-2 py-2" href="../{{ CLIENT_TAB_NOTES }}/?page1={{ notes.next_page_number }}">&#x27E9</a> {# next #}
              <a class="btn btn-outline-info mx-2 my-2 px-2 py-2" href="../{{ CLIENT_TAB_NOTES }}/?page1={{ notes.paginator.num_pages }}">&#x27EB</a> {# last #}
            {% endif %}
          </div>
          {% endif %}
          <div>
            {% if object.therapist == user %}
            <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{% url 'ccf:note-create' object.id %}">Add Note</a>
            {% endif %}
          </div>
        </div>
        <div class="tab-pane {{ tab_to_open|active_tab:CLIENT_TAB_TREATMENTS }}" id="simple-tabpanel-2" role="tabpanel">
          <table class="table table-sm table-hover table-bordered" style="width:auto">
          {% for treatment in treatments %}
          <tr>
            <td><a href="{% url 'ccf:treatment-detail' client_id=object.id pk=treatment.id %}">{{ treatment.title }}</a></td>
            <td>{{ treatment.date_treated|date:"d M Y" }}</td>
            <td>{{ treatment.content|truncate_field:'40' }}</td>
          </tr>
          {% empty %}
          Client has no treatments
          {% endfor %}
          </table>
          {% if treatments.is_paginated %}
          <div>
            {% if treatments.has_previous %}
              <a class="btn btn-outline-info mx-2 my-2 px-2 py-2" href="../{{ CLIENT_TAB_TREATMENTS }}/?page2=1">&#x27EA</a> {# first #}
              <a class="btn btn-outline-info mx-2 my-2 px-2 py-2" href="../{{ CLIENT_TAB_TREATMENTS }}/?page2={{ treatments.previous_page_number }}">&#x27E8</a> {# previous #}
            {% endif %}
            {% for num in treatments.paginator.page_range %}
              {% if treatments.number == num %}
                <a class="btn btn-info mx-2 my-2 px-2 py-2" href="../{{ CLIENT_TAB_TREATMENTS }}/?page2={{ num }}">{{ num }}</a>
              {% elif num > treatments.number|add:'-3' and num < treatments.number|add:'3' %}
                <a class="btn btn-outline-info mx-2 my-2 px-2 py-2" href="../{{ CLIENT_TAB_TREATMENTS }}/?page2={{ num }}">{{ num }}</a>
              {% endif %}
            {% endfor %}
            {% if treatments.has_next %}
              <a class="btn btn-outline-info mx-2 my-2 px-2 py-2" href="../{{ CLIENT_TAB_TREATMENTS }}/?page2={{ treatments.next_page_number }}">&#x27E9</a> {# next #}
              <a class="btn btn-outline-info mx-2 my-2 px-2 py-2" href="../{{ CLIENT_TAB_TREATMENTS }}/?page2={{ treatments.paginator.num_pages }}">&#x27EB</a> {# last #}
            {% endif %}
          </div>
          {% endif %}
          {% if object.therapist == user %}
          <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{% url 'ccf:treatment-create' object.id %}">Add Treatment</a>
          {% endif %}
        </div>
        <div class="tab-pane {{ tab_to_open|active_tab:CLIENT_TAB_MEDICAL }}" id="simple-tabpanel-3" role="tabpanel">
          <table class="table table-sm table-hover table-bordered" style="width:auto">
          {% for label, value in medical.get_detail_fields %}
            <tr>
              <td><b>{{ label }}</b></td>
            </tr>
            <tr>
              <td>{{ value|linebreaks|truncate_field:'5000' }}</td>
            </tr>
          {% empty %}
          Client has no medical data
          {% endfor %}
          </table>
          {% if object.therapist == user %}
          <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{% url 'ccf:medical-update' object.id %}">Update</a>
          {% endif %}
        </div>
        <div class="tab-pane {{ tab_to_open|active_tab:CLIENT_TAB_CONSULTATION }}" id="simple-tabpanel-4" role="tabpanel">
          <table class="table table-sm table-hover table-bordered" style="width:auto">
          {% for label, value in consultation.get_detail_fields %}
            <tr>
              <td><b>{{ label }}</b></td>
            </tr>
            <tr>
              <td>{{ value|linebreaks|truncate_field:'5000' }}</td>
            </tr>
          {% empty %}
          Client has no consultation data
          {% endfor %}
          </table>
          {% if object.therapist == user %}
          <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{% url 'ccf:consultation-update' object.id %}">Update</a>
          {% endif %}
        </div>
      </div>
    </div>
  </article>
{% endblock content %}

ccf/templates/ccf/client_form.html
{% extends "ccf/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
  <div class="content-section">
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    {{ form.media }}  {# Adds widget's JS/CSS files from CDN #}
    <form method="POST">
      {% csrf_token %}
      <fieldset class="form-group">
        <legend class="border-bottom mb-4">Client</legend>
        {{ form|crispy }}
      </fieldset>
      <div class="form-group">
        <button class="btn btn-outline-info" type="submit">Add</button>
      </div>
    </form>
  </div>
{% endblock content %}

ccf/templates/ccf/generic_add_update_form.html
{% extends "ccf/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
  <div class="content-section">
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    {{ form.media }}  {# Adds widget's JS/CSS files from CDN #}
    <form method="POST">
      {% csrf_token %}
      <fieldset class="form-group">
        <legend class="border-bottom mb-4">{{ title }}</legend>
        {{ form|crispy }}
      </fieldset>
      <div class="form-group">
        <button class="btn btn-outline-info" type="submit">{{ action }}</button>
        {% if model == 'User' %}
        <a class="btn btn-outline-secondary" href="{% url cancel_url user %}">Cancel</a>
        {% else %}
        <a class="btn btn-outline-secondary" href="{% url cancel_url client_id=view.kwargs.client_id tab=client_tab %}">Cancel</a>
        {% endif %}
      </div>
    </form>
  </div>
{% endblock content %}

ccf/templates/ccf/generic_confirm_delete.html
{% extends "ccf/base.html" %}
{% block content %}
  <div class="content-section">
    <form method="POST">
      {% csrf_token %}
      <fieldset class="form-group">
        <legend class="border-bottom mb-4">Delete {{ model }}</legend>
        <h2>Are you sure you want to delete {{ model|lower }} "{{ generic_object.display_name }}"</h2>
      </fieldset>
      <div class="form-group">
        <button class="btn btn-outline-danger" type="submit">Yes, Delete</button>
        <a class="btn btn-outline-secondary" href="{{ generic_object.get_absolute_url }}">Cancel</a>
      </div>
    </form>
  </div>
{% endblock content %}